[Monorail] Allow local dev to create one MonorailConnection per shard
When testing threading code that uses MySQL cursors locally, weird errors
started popping up, for instance:
OperationalError: (2006, 'MySQL server has gone away')

This is due to local dev mode only using one MonorailConnection and that the
MySQL cursor module in Python is not threadsafe ("Don't share connections
between threads.")[1]. Despite there still only being one database locally,
allowing Monorail to create multiple connections (one per shard) fixes
these threading problems.

[1] http://mysql-python.sourceforge.net/MySQLdb.html#functions-and-attributes

Bug: monorail:
Change-Id: I2911745815e86d60433f070188c7a91b823d565d
Reviewed-on: https://chromium-review.googlesource.com/952573
Commit-Queue: Jeff Carpenter <jeffcarp@chromium.org>
Reviewed-by: Jason Robbins <jrobbins@chromium.org>