Revert "Remove SVN support from lkgr_finder"
This reverts commit b24a953db287b83c6725422537fad5e869d7c073.

Reason for revert: Breaks lkgr finders. See logs, sample error:
  File ".../infra/services/lkgr_finder/__main__.py", line 313, in <module>
    sys.exit(main(sys.argv[1:]))
  File ".../infra/services/lkgr_finder/__main__.py", line 235, in main
    lkgr = lkgr_lib.FetchLKGR(config['status_url'] + repo.status_path)
AttributeError: 'GitWrapper' object has no attribute 'status_path'


TBR=agable@chromium.org,bpastene@google.com,bpastene@chromium.org,chromium-reviews@chromium.org,infra-reviews+infra@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Change-Id: I96c83a66ce0c94e4b99544521ca1017d9950b7ec
Reviewed-on: https://chromium-review.googlesource.com/404248
Commit-Queue: Michael Achenbach <machenbach@chromium.org>
Reviewed-by: Michael Achenbach <machenbach@chromium.org>