Revert "Use committer date in bugdroid messages"
This reverts commit d27ac0b230bedae4bc968515b02927cf9e17c2b7.

Reason for revert: AttributeError: 'GitLogEntry' object has no attribute 'commiter_date'

BUG=687515

Original change's description:
> Use committer date in bugdroid messages
> 
> This reduces confusion when CLs that may have been uploaded
> hours or days apart are landed in rapid succession.
> 
> BUG=686983
> 
> Change-Id: I88e5431aefedcc69c118ad35566bc0fae54ba77c
> Reviewed-on: https://chromium-review.googlesource.com/435033
> Commit-Queue: Aaron Gable <agable@chromium.org>
> Reviewed-by: Sean McCullough <seanmccullough@chromium.org>
> 

TBR=agable@chromium.org,seanmccullough@chromium.org,chromium-reviews@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=686983

Change-Id: Id562c53231acc5ba3ce3ce10c109afd08bfb803e
Reviewed-on: https://chromium-review.googlesource.com/435745
Commit-Queue: Dave Sansome <dsansome@chromium.org>
Reviewed-by: Dave Sansome <dsansome@chromium.org>