Disable continuous building of android cipd packages.
It keeps closing the infra tree due to:
Error: timeout while waiting for CAS service to finalize the upload.

TBR=vadimsh@chromium.org
Bug:
Change-Id: Ie2b846a6544ea070dc393ea8dd3f305271e5657f
Reviewed-on: https://chromium-review.googlesource.com/506625
Reviewed-by: Benjamin Pastene <bpastene@chromium.org>
Commit-Queue: Benjamin Pastene <bpastene@chromium.org>