chromium-cq-status: Fix invalid type passing in false reject stats analysis
This change fixes the following error while building new CQStats.
File "/base/data/home/apps/s~chromium-cq-status/highend:9465d8b-alancutter.380175972011001906/stats/patchset_stats.py", line 230, in has_any_actions
    if action in actions:
TypeError: 'in <string>' requires string as left operand, not NoneType

TBR=sergeyberezin@chromium.org
BUG=434121

Review URL: https://codereview.chromium.org/730223005