[Findit] Fix for TypeError: unhashable type: 'dict'
Stack Trace:
TypeError: unhashable type: 'dict'
at _GetSwarmingTaskAndTryJobForFailure (/base/data/home/apps/s~findit-for-me/18023-b8d7f5c.412971483831798704/endpoint_api.py:504)
at _GenerateResultsForBuild (/base/data/home/apps/s~findit-for-me/18023-b8d7f5c.412971483831798704/endpoint_api.py:592)

The failure_result_map has a format like {'step1': {'test1': 'try_job_key string', ...}, 'step2': 'try_job_key string', ...}. The issue here is, for some reason, the caller couldn't find the test_name in failure_info so it thinks it's a step failure and passed None as test_name, but the failure is actually a test failure and test_names are saved in failure_result_map.

The root cause is still unknown, this change is a work around.

Bug: 902835
Change-Id: Id48a59ef45cd1d0cb88450c1184f6e8df7e87878
Reviewed-on: https://chromium-review.googlesource.com/c/1324770
Commit-Queue: Chan Li <chanli@chromium.org>
Reviewed-by: Jeffrey Li <lijeffrey@chromium.org>
Cr-Commit-Position: refs/heads/master@{#18854}