Speculative fix for SoM crash
The crash is
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not dict

Triggered on line
logging.warn('Had to truncate blame list (%r:%r, length %d) for %s',
    last_passing, first_failing, len(blame_list), reason_key)

Which cannot happen, because len() won't return a dict.

TBR=seanmccullough@chromium.org
BUG=483529

Review URL: https://codereview.chromium.org/1121013002