[flatten_buildbucket_cfg] Bump libprotobuf to 3.6.1.
Buildbucket's _pb2.py depend on it already. Without this change
flatten_buildbucket_cfg fails with:

TypeError: __init__() got an unexpected keyword argument 'serialized_options'

R=nodir@chromium.org, tandrii@chromium.org
BUG=833946

Change-Id: Id34dac429d7b3edce9a29a0f295a53af92231aba
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/1504796
Reviewed-by: Andrii Shyshkalov <tandrii@chromium.org>
Commit-Queue: Vadim Shtayura <vadimsh@chromium.org>
Cr-Commit-Position: refs/heads/master@{#21127}