Fix deployment for tree-status
In this CL I fixed a few things for the deployments of tree status.

Currently we are having error when running "make build", the reason is the polymer version we are using is not compatible with vulcanize. It is throwing exception

(node:44814) UnhandledPromiseRejectionWarning: Error: Error parsing script in /usr/local/google/home/nqmtuan/cr/infra/go/src/infra/appengine/tree-status/bower_components/polymer/lib/legacy/class.html at NaN:NaN
TypeError: Cannot read property 'elements' of undefined

For this, we should use polymer ~2.0.0 instead of ^2.0.0 . We can look for a way to make it work with more recent version, but let's unblock the build first.

Also delete the "application" in app.yaml, based on https://cloud.google.com/appengine/docs/standard/python/config/appref, it said the field is deprecated and it is throwing errors

Also the cron.yaml should have a "cron:" at the beginning, based on https://cloud.google.com/appengine/docs/standard/python/config/cronref

I created a new version at https://25863-09fea62-tainted-nqmtuan-test-tree-status-dot-tree-status.appspot.com/, but I will wait until tomorrow to migrate the traffic to it, just in case

R=orodley@google.com

Bug: 1005557
Change-Id: I501a58ab8c31a66da7f9d085fd24497aa4b9a7f0
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/1810283
Commit-Queue: Quang Minh Tuan Nguyen <nqmtuan@google.com>
Reviewed-by: Tiffany Zhang <zhangtiff@chromium.org>
Reviewed-by: Owen Rodley <orodley@chromium.org>
Cr-Commit-Position: refs/heads/master@{#25860}