Remove duplicate strip().
It causes the following exception, if the header value is None.
: AttributeError 'NoneType' object has no attribute 'strip'

A sample error can be found at http://shortn/_bytCNRANOK.

R=jojwang

Change-Id: Id0b0022933eff8260adb426229ced9824983150e
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/1824509
Reviewed-by: Joanna Wang <jojwang@chromium.org>
Commit-Queue: Scott Lee <ddoman@chromium.org>
Cr-Commit-Position: refs/heads/master@{#26036}