[goldctl] Stop trying to build for MIPS, boltdb doesn't work on MIPS.
github.com/boltdb/bolt appears to be one of the dependencies of goldctl. It
doesn't support MIPS: https://github.com/boltdb/bolt/issues/656

This manifests as:
.../src/github.com/boltdb/bolt/db.go:101:13: undefined: maxMapSize

TBR=kjlubick@chromium.org, iannucci@chromium.org,

Change-Id: I495d80fda02a18c11376451b94930f17b3935730
Reviewed-on: https://chromium-review.googlesource.com/c/1367146
Reviewed-by: Vadim Shtayura <vadimsh@chromium.org>
Commit-Queue: Vadim Shtayura <vadimsh@chromium.org>
Cr-Commit-Position: refs/heads/master@{#19412}