[Findit] Get logdog logs using http requests instead of rpc requests.
After getting path of a specific log from annotation, send http request to get the actual log.

This should fix the root cause of https://pantheon.corp.google.com/errors/CJ2884re-tHT_AE?time=P30D&project=findit-for-me

Stack trace sample:

at UpdateTryJobMetadata (/base/data/home/apps/s~findit-for-me/waterfall-backend:18422-0726dbc.413322991900250183/services/try_job.py:492)
at OnTryJobCompleted (/base/data/home/apps/s~findit-for-me/waterfall-backend:18422-0726dbc.413322991900250183/services/try_job.py:746)
at OnTryJobStateChanged (/base/data/home/apps/s~findit-for-me/waterfall-backend:18422-0726dbc.413322991900250183/services/try_job.py:693)
at OnTryJobStateChanged (/base/data/home/apps/s~findit-for-me/waterfall-backend:18422-0726dbc.413322991900250183/services/test_failure/test_try_job.py:584)

AttributeError: 'str' object has no attribute 'get'
Change-Id: I2151490be20756baa63e3a239b792e7800ae148f
Reviewed-on: https://chromium-review.googlesource.com/c/1289610
Reviewed-by: Jeffrey Li <lijeffrey@chromium.org>
Commit-Queue: Jeffrey Li <lijeffrey@chromium.org>
Auto-Submit: Chan Li <chanli@chromium.org>
Cr-Commit-Position: refs/heads/master@{#18456}