Revert "[Findit] Track bug creation metric for flake."
This reverts commit ddc334212eac75e76b88d528104c09d69893c1de.

Reason for revert: tests failed on CI:
fatal error: .concurrent map read and map write
https://logs.chromium.org/v/?s=chromium%2Fbb%2Fchromium.infra%2Finfra-continuous-trusty-64%2F12121%2F%2B%2Frecipes%2Fsteps%2Finfra_go_tests%2F0%2Fstdout

Original change's description:
> [Findit] Track bug creation metric for flake.
> 
> This is for setting up alerts.
> 
> R=​lijeffrey,stgao,chanli,liaoyuke
> 
> Bug:836981
> Change-Id: Ibf9b582e3fb3486df7611229d70f21e0483e27df
> Reviewed-on: https://chromium-review.googlesource.com/1048039
> Reviewed-by: Roberto Carrillo <robertocn@chromium.org>
> Reviewed-by: Chan Li <chanli@chromium.org>
> Reviewed-by: Jeffrey Li <lijeffrey@chromium.org>
> Commit-Queue: Roberto Carrillo <robertocn@chromium.org>

TBR=stgao@chromium.org,robertocn@chromium.org,lijeffrey@chromium.org,chanli@chromium.org,liaoyuke@chromium.org

Change-Id: I537b721c8325152312d493944ab127e472ead20d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 836981
Reviewed-on: https://chromium-review.googlesource.com/1047888
Reviewed-by: Andrii Shyshkalov <tandrii@chromium.org>
Commit-Queue: Andrii Shyshkalov <tandrii@chromium.org>