Make --deps-file required.
Without it you get this exception:

  File "./bootstrap.py", line 268, in main
    deps = merge_deps(opts.deps_file)
  File "[snip]/bootstrap/util.py", line 81, in merge_deps
    for path in paths:
TypeError: 'NoneType' object is not iterable

BUG=

Change-Id: Ia6f9d3aa407255c18ac2ce46f2aa4200acc5d08b
Reviewed-on: https://chromium-review.googlesource.com/368092
Commit-Queue: Dave Sansome <dsansome@chromium.org>
Reviewed-by: Robbie Iannucci <iannucci@chromium.org>