Partially fix test.py on Windows.
This fix is mostly useless since expect_tests fails right away with:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "e:\b\depot_tools\python276_bin\Lib\multiprocessing\forking.py",
       line 380, in main
    prepare(preparation_data)
  File "e:\b\depot_tools\python276_bin\Lib\multiprocessing\forking.py",
       line 489, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named expect_tests

R=iannucci@chromium.org,pgervais@chromium.org
BUG=487483

Review URL: https://codereview.chromium.org/1129353007