[FindIt] Make Flake Detection recover from Monorail failures
Flake Detection can fail while trying to create or update issues due to
that it doesn't have permissions or the issue itself was deleted, and
in those cases, calling Monorail APIs raises a HttpError that looks
like the following:

googleapiclient.errors.HttpError: <HttpError 403 when requesting
https://monorail-staging.appspot.com/_ah/api/monorail/v1/projects/chromium/issues/621687?alt=json
returned "User is not allowed to view this issue chromium:621687">

This CL makes sure that Flake Detection doesn't crash when encounter
such a failure, and will continue to create or update next issues.

Bug: 864573, 873190
Change-Id: Idb3533389d75966df2af2198f2aa3711cca83f84
Reviewed-on: https://chromium-review.googlesource.com/1195942
Commit-Queue: Yuke Liao <liaoyuke@chromium.org>
Reviewed-by: Jeffrey Li <lijeffrey@chromium.org>
Cr-Commit-Position: refs/heads/master@{#17298}