Revert of gae_ts_mon: instrument Cloud Endpoint methods (patchset #11 id:200001 of https://codereview.chromium.org/1797103003/ )
Reason for revert:
Breaks all apps with the following error:

Configuration "webapp_django_version" not recognized

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/s~chromium-try-flakes/3718-78083c5.391607094608479213/main.py", line 5, in <module>
    import gae_ts_mon
  File "/base/data/home/apps/s~chromium-try-flakes/3718-78083c5.391607094608479213/gae_ts_mon/__init__.py", line 38, in <module>
    from infra_libs.ts_mon.config import initialize
  File "/base/data/home/apps/s~chromium-try-flakes/3718-78083c5.391607094608479213/gae_ts_mon/config.py", line 14, in <module>
    import endpoints
ImportError: No module named endpoints

Original issue's description:
> gae_ts_mon: instrument Cloud Endpoint methods
>
> Introducing a decorator to instrument Cloud Endpoints methods.
>
> In this version, only status and latency are measured. I'm not yet sure
> how to extract request & response sizes; they are probably not accurately
> known at the method level.
>
> BUG=570410
> R=dsansome@chromium.org,nodir@chromium.org
>
> Committed: https://chromium.googlesource.com/infra/infra/+/d6c85d91f53ea782469c4ea76345d522c37077c2

TBR=dsansome@chromium.org,nodir@chromium.org,sergeyberezin@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=570410

Review URL: https://codereview.chromium.org/1829023003