[Findit] Fix a bug when calling swarming.ListSwarmingTasksDataByTags.
When refactor swarming related logic, an error(TypeError: 'SwarmingTaskData' object has no attribute '__getitem__') was introduced in trigger_base_swarming_task_pipeline since before swarming.ListSwarmingTasksDataByTags returns a list of dict but now it returns a list of SwarmingTaskData object.

Error log: https://pantheon.corp.google.com/errors/CIKJs4Gwnq-xew?time=P1D&project=findit-for-me

Change-Id: I82ae0eb8324985473cfe8621b98d310db12d1a23
Reviewed-on: https://chromium-review.googlesource.com/961084
Reviewed-by: Brandon Wylie <wylieb@chromium.org>
Commit-Queue: Chan Li <chanli@chromium.org>