Reverting so I can deploy:
  File "/base/data/home/apps/s~monorail-staging/23169-9f0ceae.418348672660170326/registerpages.py", line 72, in <module>
    from sitewide import usercommits
ImportError: cannot import name usercommits

Revert "Monorail: Delete user commit cron and UI code."

This reverts commit dd9be0d6a3adba41b450490a1fe38329ee2e7bb7.

Reason for revert: <INSERT REASONING HERE>

Original change's description:
> Monorail: Delete user commit cron and UI code.
> 
> Notes:
> 
> The page this feature displayed on (the Polymer profile page) was never launched.
> Some regressions have happened on this page before this chance (ie: header bar doesn't work gracefully without a project specified)
> The user commits cron needs to resolve some scaleability problems before can be used on more repos than just Chrome Infra's, so as is, I think we are unlikely to invest the effort to get this feature into a launchable state in the near future.
> Having a unified activity view (even with public data) did end up poising some privacy problems, so the activity tracker only shows up for users on their own page.
> My general thinking: Pare this page down to the features that are useful for launching a replaced new profile page. I think maybe the acivity tracker can stay as a fun profile visualization of comments if we want, just without commit data.
> 
> Bug: monorail:5579
> Change-Id: Ib0f692498074a3b5623233bebf0f8b4384f341ce
> Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/1620683
> Commit-Queue: Tiffany Zhang <zhangtiff@chromium.org>
> Reviewed-by: Edward Lesmes <ehmaldonado@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#23127}

TBR=zhangtiff@chromium.org,jrobbins@chromium.org,ehmaldonado@chromium.org

Change-Id: Idd1e3b9974a59a44c04bb8b8ad1fc37acfb893a7
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: monorail:5579
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/1623345
Reviewed-by: Joanna Wang <jojwang@chromium.org>
Commit-Queue: Joanna Wang <jojwang@chromium.org>
Cr-Commit-Position: refs/heads/master@{#23131}